services:
  gatherbee:
    container_name: gatherbee
    image: gatherbee
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8700:3000"
    depends_on:
      - gatherbee-api
    env_file:
      - ./.env

  gatherbee-api:
    container_name: gatherbee-api
    image: gatherbee-api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8701:8080"
    env_file:
      - ./.env

  postgres:
    image: postgres:15
    container_name: gatherbee-database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-gatherbee}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB:-gatherbee}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gatherbee -d gatherbee"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
