services:
  gatherbee:
    container_name: gatherbee
    image: gatherbee
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - gatherbee-api
    environment:
      NEXT_PUBLIC_GATHERBEE_API_URL: http://localhost:8080

  gatherbee-api:
    container_name: gatherbee-api
    image: gatherbee-api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB: ${DB}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      AUTHENTIK_API_URL: ${AUTHENTIK_API_URL}
      CLIENT_ID: ${AUTHENTIK_CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}

  postgres:
    image: postgres:15
    container_name: gatherbee-database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-gatherbee}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB:-gatherbee}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gatherbee -d gatherbee"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
